# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

api_key: 'API Key'
domain: 'Domain'
username: 'postmaster@sandbox6f73972d6ebf46b9aa195baaa32c95d0.mailgun.org'
password: '71b31b44ce4d1e159f60e9b4cee923e6-09001d55-d9f325e2'
gmail_username: 'hakeemmidan@gmail.com'
gmail_password: 'Hakima3k*am'